Addresses bug in #1003.
FAIRsharing/fairsharing.github.io pull request #1017
Opened 2021-06-03 10:47 UTC by knirirr

This fixes the bug mentioned in ticket #1003 by adding a callback to the status dropdown that clears deprecation_reason if the status is set to other than deprecated.

2021-06-03 11:56 UTC, ramGranell approved these changes

2021-06-03 14:02 UTC, hoseinmirian requested changes
1- it shows 1 change by the first visit in generalInfo 
![image](https://user-images.githubusercontent.com/25683981/120657755-b107cf80-c47c-11eb-9b94-d75330c829c2.png)

2- it does not allow me to save depreaction reason after setting the status of record
![image](https://user-images.githubusercontent.com/25683981/120657690-a1888680-c47c-11eb-849f-59be0b681b43.png)

2021-06-03 15:09 UTC, knirirr commented
I've changed the method to clear the deprecation_reason on save rather than in the UI as it seems to be far less prone to bugs. So, deprecation_reason will remain in the text box until you click on "save".

2021-06-04 08:55 UTC, hoseinmirian approved these changes

2021-06-04 09:00 UTC, merged