Hossein changes related record #1037
FAIRsharing/fairsharing.github.io pull request #1045
Opened 2021-06-09 13:18 UTC by hoseinmirian

Please check array express record

![image](https://user-images.githubusercontent.com/25683981/121361772-7e9f1c00-c92d-11eb-99f5-28f5afca020a.png)

2021-06-09 13:42 UTC, knirirr requested changes
There's a discussion of this change here:

https://pyroeis.oerc.ox.ac.uk/#narrow/stream/8-FAIRsharing-Rebuild/topic/Front-end/near/30004

One of the records mentioned is https://deploy-preview-1045--fairsharing.netlify.app/#/FAIRsharing.tsp58, which should collect at least one record (https://deploy-preview-1045--fairsharing.netlify.app/#/FAIRsharing.q81k8w). But, there's no related records box at all.

2021-06-09 13:42 UTC, knirirr commented on src/components/Records/Record/Collections.vue
> +    <SectionTitle title="In colledted" />
```suggestion
    <SectionTitle title="Collections &amp; Recommendations" />
```

2021-06-09 13:46 UTC, knirirr commented on src/components/Records/Record/RelatedContent.vue
> +                .filter(item => _module.tabsData.tabs[tabName].registry.includes(item.registry) && item.linkType !=='fairsharingRecord' && _module.tabsData.tabs[tabName].relation.includes(item.record
The removal of this `!` has caused the breakage mentioned in the comments (disappearing related records).

2021-06-09 13:50 UTC, knirirr commented
There's one other change still needed - that is, the related records box should show outgoing recommends relationships. It appears not to do so at present (compare the two records linked above).

2021-06-10 15:12 UTC, hoseinmirian commented
please test record:
http://localhost:8080/#/FAIRsharing.dIDAzV

2021-06-10 15:33 UTC, knirirr approved these changes

2021-06-10 15:45 UTC, merged