Add restriction to records related to this organisation width to be s…
FAIRsharing/fairsharing.github.io pull request #1329
Opened 2021-11-08 18:55 UTC by hoseinmirian

now in a smaller screen the whole content of the section turns into a scrollable container and will show a scrolling bar by hovering or clicking on it. min-width would be 500 pixel/ 

please check /organisation/:anyID

<img width="395" alt="image" src="https://user-images.githubusercontent.com/25683981/140800885-3d0740ee-a54b-46dd-ade6-e70636a1a6e6.png">

2021-11-09 13:55 UTC, knirirr requested changes
If you're modifying the behaviour on small screens it would be worth changing the elements so they stack one above the other. At present on this branch the following occurs on a small screen:

![Screen Shot 2021-11-09 at 13 53 45](https://user-images.githubusercontent.com/3583375/140936725-188d72a0-73cc-4260-bda6-f6c310438f76.png)

2021-11-09 14:35 UTC, hoseinmirian commented
@knirirr requested changes applied
<img width="851" alt="image" src="https://user-images.githubusercontent.com/25683981/140943513-62f4f467-90db-460d-8a92-2421906d8cee.png">

2021-11-09 15:08 UTC, knirirr requested changes
Looks better, thanks. Can anything be done about the alignment of text in the related records section, on small screens?

![Screen Shot 2021-11-09 at 15 06 28](https://user-images.githubusercontent.com/3583375/140949730-36081b73-a4d8-4ca2-b88f-f8e8e91515c8.png)

If so then this PR could also address https://github.com/FAIRsharing/fairsharing.github.io/issues/1319

2021-11-10 11:26 UTC, knirirr approved these changes

2021-11-10 12:19 UTC, merged