Add orcid style to icons in record display
FAIRsharing/fairsharing.github.io pull request #1360
Opened 2021-11-16 16:32 UTC by hoseinmirian

followed and pasted the exact compact version of showing orcid in record display:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/25683981/142026125-5e4a7201-c921-4586-a6b0-ebe2ff9c0f6f.png">

please test:
http://localhost:8080/FAIRsharing.2abjs5

2021-11-16 16:45 UTC, knirirr requested changes
The record page was already acceptable under ORCID's requirements, i.e. we had put an ORCID logo (with link) after the username.
Where our application needs changing is on the user pages, where the ID is shown as a non-hyperlinked ID with no logo (the logo should be before the ID).

2021-11-16 17:05 UTC, hoseinmirian commented
@knirirr  this page you are referring to right?
http://localhost:8080/users/1136

2021-11-17 09:25 UTC, knirirr commented
> @knirirr this page you are referring to right? http://localhost:8080/users/1136

Yes, that's the only page that needs changing to conform to ORCID's styles.

2021-11-17 12:42 UTC, hoseinmirian commented
<img width="378" alt="image" src="https://user-images.githubusercontent.com/25683981/142202602-c8a49d27-874d-4cf5-86af-8be04e79d1cb.png">

2021-11-17 13:01 UTC, knirirr requested changes
Various spurious "None" entries are now appearing next to data fields:

https://deploy-preview-1360--fairsharing.netlify.app/#/users/1136

I think my suggested change will fix it.

2021-11-17 13:01 UTC, knirirr commented on src/views/Users/PublicProfile.vue
> +                        <span> None </span>
```suggestion
                        <span v-else> None </span>
```

2021-11-17 13:11 UTC, knirirr approved these changes

2021-11-17 13:11 UTC, merged