Hossein fix network color #1409
FAIRsharing/fairsharing.github.io pull request #1430
Opened 2021-12-15 10:43 UTC by hoseinmirian

Now each node color will be according to their status: (ready:green, etc)

2021-12-15 11:26 UTC, knirirr requested changes
The code looks OK, but we'll need a key in the sidebar to the left to inform users which colours relate to which statuses.

2021-12-15 12:33 UTC, allysonlister commented
Thank you, this now seems to be working as expected. We now have an additional issue that wasn't clear to me until we had this build to look at.

Deprecated and Uncertain are both grey in FAIRsharing. I am talking to Susanna to see about perhaps changing one of the greys. Thanks!

2021-12-16 16:08 UTC, knirirr commented
I think this looks good (and will approve in a moment) but I presume we'll be waiting until @allysonlister hears back before it can be merged.

2021-12-16 16:09 UTC, knirirr approved these changes

2021-12-17 09:47 UTC, allysonlister requested changes
Please could you add this new text underneath "Record Status", as there is no explanation of what record status is in the context of the graph.

"The colour of each point represents the life cycle status of that resource as shown in the legend below."

2021-12-17 10:18 UTC, knirirr commented
What was the result of:

>  I am talking to Susanna to see about perhaps changing one of the greys. 

Are the colours acceptable, or do we need to wait?

2021-12-17 11:04 UTC, allysonlister commented
My apologies - trying to catch up on a Friday hasn't worked as well as I had hoped :-)

Yes, she has no strong preference. However, whichever color we use for deprecated records should be the same across the site.

I would like to suggest a FAIRsharing red / maroon for deprecated, though that might be a bit bright and would have to be sufficiently different from the red color that the central node in the graph is using. Do you have any suggestions?

2021-12-17 11:19 UTC, knirirr commented
I have none, so if you don't either I'll leave this to @hoseinmirian to make changes and re-request review; I am already satisfied with everything in this PR.

2021-12-17 11:19 UTC, hoseinmirian commented
lets see how your suggestion look @allysonlister I have no preference for now.

2021-12-17 11:21 UTC, allysonlister commented
Thanks - let me know when the updated color has been implemented please :)

2021-12-17 11:25 UTC, hoseinmirian commented
actually I have an opinion. maybe brown would be good due to deprecated means somehow old and old color reminds us always like gray, black and brown mostly. old movie old images used to be gray or brownish... if that makes sense? what do u think?

2021-12-17 12:05 UTC, allysonlister commented
A shade of brown sounds good - please just make sure it is sufficiently different from "in development"'s color. Thanks very much!

2021-12-17 13:57 UTC, hoseinmirian commented
@allysonlister its ready to review. Updated the color of deprecated to brown. 

@knirirr : LightenDarkenColor added in generalUtils due to the previous third party was causing issue with test, this one is tested and can be used in the future. Also another improvement to look is where I used the lightenDarkenColor js function to programmatically changing the gradient of record status background and also all the color now are loading from theme,js which everytime we need to change the color just need to change theme.js and it applies on record status and elsewhere.

2021-12-17 14:02 UTC, knirirr commented
@hoseinmirian looks like coverage has dropped, which will need fixing.

2021-12-17 14:06 UTC, allysonlister requested changes
> please just make sure it is sufficiently different from "in development"'s color. Thanks very much!

Thanks, but the "in development" color and the "deprecated" color are now very similar. Perhaps introduce a little bit of red into the deprecated color?

2021-12-17 14:35 UTC, hoseinmirian commented on tests/unit/utils/generalUtils.spec.js
> +    it("can check vvv", function () {
```suggestion
it("can check getHostName method",function(){
```

2021-12-17 14:37 UTC, hoseinmirian commented on tests/unit/utils/generalUtils.spec.js
> +    it("capitalises aaa", function () {
```suggestion
    it("can check LightenDarkenColor function", function () {
```

2021-12-17 14:46 UTC, hoseinmirian commented
@knirirr and @allysonlister ready for review

2021-12-17 14:49 UTC, allysonlister approved these changes
thanks - this looks great now!

2021-12-17 16:05 UTC, knirirr approved these changes

2021-12-17 17:35 UTC, merged