Add banner expiry into localstorage and its functional now
FAIRsharing/fairsharing.github.io pull request #1462
Opened 2022-01-11 18:13 UTC by hoseinmirian

2022-01-12 13:33 UTC, hoseinmirian commented
failed or success banner in record display now remains 2 days and then disappears. I am confident but you can give it 2 days to see if that works and then approve the branch. tnx

2022-01-12 13:50 UTC, hoseinmirian commented on src/views/Records/Record.vue
> +              _module.showBanner = !(expiryDate.getTime() + (DAY * 24 * 60 * 60 * 1000) < now.getTime());
day * hour * min * sec * 1000 = time as milisecond.

2022-01-13 09:04 UTC, allysonlister commented
Please could you re-commit to 1 minute for now, as you suggest? 2 days from now is the weekend and I don't think I'll check then :-D thanks!

2022-01-13 10:07 UTC, hoseinmirian commented
please visit a new record and ask for review(a record u never ask for maintenance):
1- approve it from curator panel and give it 1 min and then refresh
2-  reject and do give it 1 min and refresh

2022-01-13 10:49 UTC, allysonlister requested changes
Thank you, the green "your request has been approved" is working as expected, as the red "rejected" banner. 

However, the initial message being displayed after the user requests ownership isn't the "your request has been submitted", but rather states that "you have already submitted a request". See gif below.
![already](https://user-images.githubusercontent.com/143586/149314788-e3fde5fe-7151-4546-ba31-a522a7b830bf.gif)

2022-01-13 10:54 UTC, knirirr approved these changes
This looks OK to me, though I agree with @allysonlister that different text would be better.

2022-01-13 12:40 UTC, hoseinmirian commented
@allysonlister if I replace the wording with urs is all fine?

2022-01-13 13:18 UTC, allysonlister commented
Thanks!

@hoseinmirian - just to be explicit, here is some text you can use instead:

"Your ownership request for this record has been submitted. We will get back to you within a few working days."

2022-01-13 13:37 UTC, allysonlister approved these changes
Thank you!

2022-01-13 13:37 UTC, merged