Hossein hardcoded additional fields #1253
FAIRsharing/fairsharing.github.io pull request #1565
Opened 2022-03-01 15:55 UTC by hoseinmirian

Refactored AdditonalInfo component so now it's easy to maintain and scale.

2022-03-03 14:48 UTC, knirirr approved these changes
This looks much better, although I'd like @allysonlister or @delphinedauga to take a look when they have a moment to check they are happy with the display of the additional info. section of records.

Example:

https://deploy-preview-1565--fairsharing.netlify.app/FAIRsharing.hq12h8 (this branch)
https://fairsharing.org/FAIRsharing.hq12h8

2022-03-03 16:17 UTC, delphinedauga requested changes
The title should be "COS TOP Guidelines" instead of "Cos Top Guidelines"

2022-03-03 16:46 UTC, hoseinmirian commented
> The title should be "COS TOP Guidelines" instead of "Cos Top Guidelines"

I dynamically read the titles coming from API. and clean and capitalize them. Not possible to customize it cz I keep reading them from API.

2022-03-03 16:59 UTC, knirirr commented
> > The title should be "COS TOP Guidelines" instead of "Cos Top Guidelines"
> 
> I dynamically read the titles coming from API. and clean and capitalize them. Not possible to customize it cz I keep reading them from API.

`cleanString` in stringUtils.js could incorporate a hack to detect and modify this specific string by means of a lookup table.
This is the only appropriate means; unfortunately it is not particularly elegant.

2022-03-03 17:17 UTC, hoseinmirian commented
the problem is not just this tite. we have loads of title. if I be given a set of rules like make the first 2 words CAPITALIZE I can but we have different titles like deprecation reason, etc....

2022-03-03 20:03 UTC, hoseinmirian commented
@delphinedauga please try again.tnx

2022-03-04 09:15 UTC, knirirr commented
I've lost the ability to comment directly on the code; no idea why.
Anyway, this is the sort of thing I had in mind. I'd change `setCOS_title` to `setTitle` though; any further special cases could be added to this later, if necessary adding a JSON data structure to handle them.
Alternatively, changes to the schemas (if a separate title field can be supported) might be an option.
In any case, that's work for a later date as the code in this PR is (I think) significantly more maintainable.

2022-03-04 10:57 UTC, knirirr commented on src/components/Records/Record/AdditionalInfo/DatasetArray.vue
> +    <b class="text-h6 text-capitalize">{{ setCOS_title(cleanString(title)) }}</b>
```suggestion
    <b class="text-h6 text-capitalize">{{ setTitle(cleanString(title)) }}</b>
```

2022-03-04 10:57 UTC, knirirr approved these changes

2022-03-04 10:57 UTC, knirirr commented on src/components/Records/Record/AdditionalInfo/DatasetArray.vue
> +    setCOS_title(title) {
```suggestion
    setTitle(title) {
```

2022-03-04 10:58 UTC, knirirr commented on src/components/Records/Record/AdditionalInfo/DatasetArray.vue
> +    setCOS_title(title) {
Looks like the code editing button has reappeared.

2022-03-04 11:03 UTC, knirirr commented on tests/unit/components/Records/Record/AdditionalInfo/DatasetArray.spec.js
> +        expect(wrapper.vm.setCOS_title(title)).toMatch("COS TOP Guidelines");
```suggestion
        expect(wrapper.vm.setTitle(title)).toMatch("COS TOP Guidelines");
```

2022-03-04 11:04 UTC, knirirr commented on tests/unit/components/Records/Record/AdditionalInfo/DatasetArray.spec.js
> +        expect(wrapper.vm.setCOS_title(title)).toMatch("anything else");
```suggestion
        expect(wrapper.vm.setTitle(title)).toMatch("anything else");
```

2022-03-04 11:07 UTC, delphinedauga approved these changes
Perfect ! Thanks !

2022-03-04 11:07 UTC, allysonlister approved these changes
I'm not sure how completely this changes fields in Additional Information, or if it's just for the COS TOP Guidelines, but I'm happy with the way it looks now based on the example that @knirirr asked us to check only. Please note that in future, COS might get back to us about how they would like this section displayed, so future modifications might be requested.

2022-03-04 11:50 UTC, merged