Added a confirmation dialog for claiming records #1675.
FAIRsharing/fairsharing.github.io pull request #1677
Opened 2022-05-24 14:24 UTC by knirirr

I've added a dialog along the lines of existing ones.

2022-05-24 15:20 UTC, ramGranell approved these changes

2022-05-25 07:15 UTC, allysonlister requested changes
Thank you - the functionality is correct, however there are a few things please:
1. I noticed a typo in my text for the popup - please would you replace "doing so will allows them to" with "doing so allows them to" (remove the "will").
2. The size of the text is rather large - could we shrink it a bit?
3. When I shrink the browser window size the popup stays the same size. If this is too difficult then don't worry about it, having slightly smaller text as described in point 2 should suffice.

Thanks!

2022-05-25 07:58 UTC, knirirr commented
I can't do anything about point 3 but the others can be addressed (that offending word was on a line wrap and so hard to spot).

2022-05-25 09:18 UTC, allysonlister approved these changes
Thank you - looks good!

2022-05-25 09:58 UTC, merged