fixed advancedSearch bug
FAIRsharing/fairsharing.github.io pull request #175
Opened 2020-03-13 16:05 UTC by hoseinmirian

2020-03-13 16:16 UTC, terazus requested changes
- [ ] Missing some unit tests (need 100% coverage).
- [ ] Missing code documentation.
- [x] Reset button should reset all filters. It does not anymore (see https://dev--fairsharing.netlify.com/ behaviour)
The autocomplete fields should be redesigned pretty soon anyway so this is not useful ATM.

2020-03-13 18:26 UTC, terazus requested changes

2020-03-13 18:26 UTC, terazus commented on src/components/Records/SearchFilters.vue
> +                if (filter.hasOwnProperty('key')) {
Replace with Object.prototype.hasOwnProperty.call(objectName, fieldName)

2020-03-13 18:33 UTC, closed without merging

2020-03-14 09:54 UTC, hoseinmirian commented on src/components/Records/SearchFilters.vue
> +                if (filter.hasOwnProperty('key')) {
ok thanks.