Resend validation 126
FAIRsharing/fairsharing.github.io pull request #428
Opened 2020-08-21 09:52 UTC by knirirr

Please note that though this is functional, the appearance needs work. Please feel free to modify the look of the button etc. to whatever you consider appropriate.

2020-09-07 14:42 UTC, ramGranell approved these changes

2020-09-10 15:59 UTC, terazus requested changes

2020-09-10 15:59 UTC, terazus commented on src/views/Users/Login/Login.vue
> +              <span v-show="resendButton">
use v-if instead of v-show.
the difference if that v-if rebuild that part of the DOM where v-show is just a css display: none attribute

2020-09-10 15:59 UTC, terazus commented on src/views/Users/Login/ResendConfirmation.vue
> +<template>
This HTML structure needs to be reviewed as it breaks the menu of the login button:
![image](https://user-images.githubusercontent.com/6538906/92758589-bb5cc900-f343-11ea-94d9-b3c3636c4798.png)

2020-09-11 11:53 UTC, hoseinmirian approved these changes

2020-09-14 13:38 UTC, knirirr commented
I have moved the form to a separate page.
I'm still not entirely satisfied with this, particularly the button to go to the new page, and may need some assistance.

2020-09-14 16:30 UTC, terazus approved these changes

2020-09-14 16:46 UTC, merged