Hossein auto complete scrolling bug #460
FAIRsharing/fairsharing.github.io pull request #468
Opened 2020-09-15 13:41 UTC by hoseinmirian

2020-09-15 14:08 UTC, knirirr reviewed
Is this commit to fix the problem of autocomplete dropdowns staying in position when the screen scrolls? If so then I'm still seeing the bug on my system when I check this branch out.

2020-09-15 15:03 UTC, terazus commented
> 
> 
> Is this commit to fix the problem of autocomplete dropdowns staying in position when the screen scrolls? If so then I'm still seeing the bug on my system when I check this branch out.

same here

2020-09-15 15:06 UTC, hoseinmirian commented
> 
> 
> Is this commit to fix the problem of autocomplete dropdowns staying in position when the screen scrolls? If so then I'm still seeing the bug on my system when I check this branch out.

yes it is. it should be fine.

2020-09-15 16:31 UTC, terazus requested changes
Not working as intended, the behaviour is still here (only the scroll bar has disaper. You now need to scroll locking of the left panel.
After that you to also sort the two position: small height and full height.

2020-10-02 12:46 UTC, knirirr commented
The latest change does appear to fix the scroll issue, which is good. However, it has affected the appearance of elements within the dropdown, which now seem to overflow (I'm using Firefox, BTW). Counts with one digit fit, two causes the element to touch the edge of the dropdown, and a third digit causes the overflow.

<img width="450" alt="Screenshot 2020-10-02 at 13 45 41" src="https://user-images.githubusercontent.com/3583375/94924583-b52aba00-04b5-11eb-8a1f-09a767caad10.png">
<img width="577" alt="Screenshot 2020-10-02 at 13 41 57" src="https://user-images.githubusercontent.com/3583375/94924592-b78d1400-04b5-11eb-904a-123e1324f494.png">

2020-10-02 13:55 UTC, knirirr approved these changes
Please wait for @terazus to review also before merging - thanks.

2020-10-05 11:08 UTC, terazus requested changes
Please merge from dev before i do the review :)

2020-10-05 12:58 UTC, terazus requested changes
Minor modifications and we are good to merge.

2020-10-05 12:58 UTC, terazus commented on src/components/Records/Search/Input/SearchInput.vue
> +  /please do not remove this function/
Please keep these commented functions either on a local branch or on a separate branch. What you submit ends up on master and unused code shouldn't be merged.

2020-10-05 12:58 UTC, terazus commented on src/components/Records/Search/Input/FilterAutocomplete.vue
> +          } else {
Stroustrup on all if/else catch/try plz.

2020-10-05 12:58 UTC, terazus commented on tests/unit/store/uiController.spec.js
> +        expect(actions.commit).toHaveBeenCalledTimes(1);
use haveBeenCalledWith **if possible**.

2020-10-08 10:01 UTC, terazus approved these changes

2020-10-08 17:55 UTC, merged