Hossein clean store #729
FAIRsharing/fairsharing.github.io pull request #746
Opened 2021-03-02 10:40 UTC by hoseinmirian

Clean records store before destroy  ...

2021-03-02 12:16 UTC, terazus requested changes
Even though the coverage is 100% you may be missing an expect statement in your records.spec.js test suite.
You want to make sure that when the component is destroyed the states have been correctly reset so something like:
`expect(recordsStore.records.length).toBe(0);
expect(recordsStore.facets.length).toBe(0);
["hits, "loading", ...].forEach(val => {
    expect(recordsStore[val]).toBe(null);
})`
Alternativerly, instead of expecting from the store, you can expect a computed property, if bound through a mapState:
`expect(wrapper.vm.records.length).toBe(0)`

2021-03-02 12:26 UTC, terazus commented
> Alternativerly, instead of expecting from the store, you can expect a computed property, if bound through a mapState:
> `expect(wrapper.vm.records.length).toBe(0)`

Actually no, you can't do that sorry. Because the component should be destroyed, wrapper.vm shouldn't be available anymore.

2021-03-03 11:27 UTC, knirirr approved these changes

2021-03-04 12:09 UTC, terazus approved these changes

2021-03-04 12:36 UTC, merged