Problems testing #773.
FAIRsharing/fairsharing.github.io pull request #778
Opened 2021-03-08 17:01 UTC by knirirr

Code seems mostly to work but tests are incomplete/failing.

2021-03-10 11:36 UTC, ramGranell approved these changes

2021-03-10 14:23 UTC, terazus approved these changes

2021-03-10 17:12 UTC, terazus requested changes
I think we need to handle 404 when user is not found.
Example:
![image](https://user-images.githubusercontent.com/6538906/110669012-c40e4a80-8180-11eb-830e-72ecd469584d.png)

2021-03-16 11:42 UTC, terazus approved these changes

2021-03-16 11:48 UTC, merged