Hossein licence #813
FAIRsharing/fairsharing.github.io pull request #890
Opened 2021-04-15 14:20 UTC by hoseinmirian

2021-04-16 14:07 UTC, knirirr commented
Unfortunately this still refers to the old API in the sections "API Access", "API versions" and "API changes". These will all have to be replaced with a single API section making reference to a new API page, which should include this content:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/README_REST.md

It's Markdown, but that's presumably easy enough to convert to HTML.

2021-04-16 14:08 UTC, knirirr requested changes
Removing the API sections as in the previous comments and replacing it with "For information on the API please go to <link>"  (or similar) is needed.

2021-04-16 14:12 UTC, hoseinmirian commented
@knirirr thanks for comments. in regard to HTML page if it is static yet its easy but due to I read from a string data in a json file it can be more difficult tho. I need to see if I can make it into a dynamic file reading from json otherwise I just use static HTML code.

2021-04-16 14:13 UTC, knirirr commented
A static page is fine here as it's not something that is likely to be changed often.

2021-04-20 08:18 UTC, knirirr commented
Now we have a different problem; the rendered markdown looks good, but it must be a separate page from the licence information. I.e. we still need this: https://fairsharing.org/licence
But, without this section, replacing it with a link to the new API instructions:

<img width="1646" alt="Screenshot 2021-04-20 at 09 16 04" src="https://user-images.githubusercontent.com/3583375/115362359-5b6fb000-a1b9-11eb-8d1f-b49f3fa92570.png">

2021-04-20 08:19 UTC, knirirr requested changes
Still not the correct content (see previous comment).

2021-04-20 11:17 UTC, knirirr commented on src/views/Static/License/License.vue
> +    </p>
```suggestion
    </p>
    
    <pre>&lt;img src="https://fairsharing.org/static/img/home/svg/FAIRsharing-logo.svg" alt="FAIRsharing Logo"&gt;</pre>

```

2021-04-20 11:21 UTC, knirirr commented on src/views/Static/License/License.vue
> +      In order to get full detail about how to use FAIRsharing API please visit <router-link
```suggestion
      For details of how to use the FAIRsharing API please visit <router-link
```

2021-04-20 11:41 UTC, knirirr approved these changes
This should do once the changes I've suggested below are incorporated.

2021-04-20 12:01 UTC, merged