Fix the Collection and related content presentation bug with a collec…
FAIRsharing/fairsharing.github.io pull request #898
Opened 2021-04-16 14:08 UTC by hoseinmirian

to check that is not now showing collection data for a collection record please test:
http://localhost:8080/#/3474

to see if still working properly with other records test any random record or array express as a suggestion
http://localhost:8080/#/FAIRsharing.6k0kwd

2021-04-16 14:38 UTC, knirirr requested changes
It seems that nothing at all is turning up in "related content" for collections. is `prepareAssociations` still filtering out any "collects" or "recommends" relations from these data?

2021-04-20 08:50 UTC, knirirr commented
Clarification from our meeting:

"in collections/recommendations" => Any reverseRecordAssociation where the label is "collects" or "recommends".
"related content" => Any recordAssociation where the label is NOT "deprecates".

2021-04-20 16:59 UTC, knirirr requested changes
With the changes I've made a collection will show standards and databases that it collects properly.
But, it can also collect policies and other collections; you might well have to add two more tabs to cover this.

2021-04-20 16:59 UTC, knirirr commented on src/components/Records/Record/RelatedContent.vue
> +          related_standards: {relation: ['collects', 'recommends', 'deprecates'], registry: "Standard", data: []},
```suggestion
          related_standards: {relation: ['deprecates'], registry: "Standard", data: []},
```

2021-04-20 16:59 UTC, knirirr commented on src/components/Records/Record/RelatedContent.vue
> +          related_databases: {relation: ['collects', 'recommends', 'deprecates'], registry: "Database", data: []}
```suggestion
          related_databases: {relation: ['deprecates'], registry: "Database", data: []}
```

2021-04-21 09:55 UTC, knirirr commented
Further comments at https://pyroeis.oerc.ox.ac.uk/#narrow/pm-with/10,18-pm/near/28168

2021-04-21 16:42 UTC, hoseinmirian commented
New tab added for relatedContent section name "Other Related Records" that collects any other records excluding those with registries standards and databases 

for testing a non-collection record to see there is no other related records tab please check:
http://localhost:8080/#/1827

and to see the tab shows up in a collection record please check:
http://localhost:8080/#/3449

2021-04-22 09:27 UTC, knirirr approved these changes

2021-04-22 09:45 UTC, merged