Hossein deprecation link #828
FAIRsharing/fairsharing.github.io pull request #939
Opened 2021-05-11 18:32 UTC by hoseinmirian

Other record tab added in the InCollection 
other related records tab added in relatedContent
tests remained covered.

2021-05-12 15:39 UTC, knirirr commented on src/components/Records/Record/RelatedContent.vue
>            related_databases: {relation: ['deprecates'], registry: "Database", data: []},
```suggestion
          related_databases: {relation: [], registry: "Database", data: []},
```

2021-05-12 15:39 UTC, knirirr commented on src/components/Records/Record/RelatedContent.vue
>            related_standards: {relation: ['deprecates'], registry: "Standard", data: []},
```suggestion
          related_standards: {relation: [], registry: "Standard", data: []},
```

2021-05-12 15:42 UTC, knirirr requested changes
Currently, this branch doesn't show records deprecated by the record being viewed. The suggested changes _should_ fix that; please look at the Genbank record to be certain; this should have one deprecation association and one deprecation reverse association, for testing purposes.

2021-05-12 16:01 UTC, hoseinmirian commented
@knirirr thank you. its fixed. now it shows their reverse relationship.

2021-05-13 09:05 UTC, knirirr approved these changes

2021-05-13 09:08 UTC, merged