Hossein additional info record #926
FAIRsharing/fairsharing.github.io pull request #941
Opened 2021-05-12 13:40 UTC by hoseinmirian

added all additional information tab fields in general info provided is available. 

test record:
http://localhost:8080/#/FAIRsharing.6k0kwd

2021-05-12 15:25 UTC, knirirr requested changes
Please put the "additional information" as a separate section - I'd suggest adding it at the bottom. 

Also, the current implementation has hard-coded the fields. The editing form uses a query to determine which additional fields are used for a particular model; see https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/store/editor.js#L225-L232

If you were to run this query and use it to determine whether or not to show additional fields, and which ones to show, then it would also resolve #942 (that should appear as an additional field).

2021-05-17 11:44 UTC, hoseinmirian commented
@knirirr all the behavior is applied based on curators feedback. If any additional fields add or delete the record display react accordingly. for test you can edit any record additional information from editing system.

2021-05-19 09:58 UTC, knirirr requested changes
Currently, the additional info. section displays for collections.
But, there's only ever one additional field that applies to collections (reference URL) and due to https://github.com/FAIRsharing/fairsharing.github.io/issues/948 it will have to go into the general information section. So, this section will have to not be displayed for collections.

2021-05-20 10:52 UTC, knirirr approved these changes

2021-05-20 11:00 UTC, merged